version: '2.1'

services:
  ydb:
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    container_name: ydb-local
    hostname: localhost
    environment:
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765
      - YDB_USE_IN_MEMORY_PDISKS=true
      - YDB_DEFAULT_LOG_LEVEL=NOTICE
    ports:
      - "2136:2136"
      - "8765:8765"
